tunnel: 94bf36f8-ff4e-4fd1-9456-6c4836789c75
credentials-file: /kaggle/working/cloudflared/94bf36f8-ff4e-4fd1-9456-6c4836789c75.json

ingress:
  - hostname: juesire.cfargotunnel.com  # 你在 Cloudflare 上的公共主机名
    service: http://127.0.0.1:8188  # ComfyUI 在 Kaggle 上运行的本地端口（假设 ComfyUI 运行在 8188 端口）
  - service: http_status:404  # 默认行为：返回 404 错误

logfile: /var/log/cloudflared.log  # 指定日志文件路径
metrics: 127.0.0.1:20242 # 可以选择开启 metrics 服务器用于监控
